title: Li Lei's Blog
author: Lilei
email: lilei03@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just one another github user's testing blog

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
